config/routes.rb
Rails.application.routes.draw do
  # resources :users, only: [:edit, :update] do
  #   collection do

  #   end
  # end
  resources :superpowers, only: [:index, :show, :new, :create, :edit, :update, :destroy] do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:destroy, :edit, :update] do
    resources :reviews, only: [:new, :create]
  end
  devise_for :users
  root to: 'pages#home'
  get 'dashboard', to: 'pages#dashboard'

  resources :users, only: [:edit, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :superpower
  has_one :review, dependent: :destroy
  validates :date, presence: true
  validate :date_cannot_be_in_the_past

  def date_cannot_be_in_the_past
    errors.add(:date, "can't be in the past") if date.present? && date < Date.today
  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  belongs_to :user
  validates :rating, presence: true, inclusion: { in: [0, 1, 2, 3, 4, 5] }
  validates :rating, numericality: { only_integer: true }

  def blank_stars
    5 - self.rating
  end
end

app/models/superpower.rb
class Superpower < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings
  has_many :reviews, through: :bookings
  validates :name, presence: true
  validates :photo, presence: true
  validates :price, numericality: { only_integer: true }
  mount_uploader :photo, PhotoUploader
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  # searchkick text_middle: [:name, :price]

  include PgSearch::Model
   pg_search_scope :search_by_name_and_price,
    against: [ :name, :price, :description ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings
  has_many :superpowers
  has_many :reviews
  has_many :reviews, through: :bookings
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :email, presence: true, uniqueness: true
  mount_uploader :photo, PhotoUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:Name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @superpower = Superpower.find(params[:superpower_id])
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @superpower = Superpower.find(params[:superpower_id])
    @booking.user = current_user
    @booking.superpower = @superpower
    if @booking.save
      redirect_to superpower_path(@superpower)
    else
      render :new
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      redirect_to dashboard_path
    else
      render :edit
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to dashboard_path
  end


private

  def booking_params
    params.require(:booking).permit(:date, :superpower_id, :user_id)
  end


end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home

  end

  def dashboard
    @user = current_user
    @superpowers = current_user.superpowers

  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @booking = Booking.find(params[:booking_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @booking = Booking.find(params[:booking_id])
    @review.user_id = current_user.id
    @review.booking_id = @booking.id
    if @review.save
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def show
  end

  private

  def review_params
    params.require(:review).permit(:rating, :description)
  end
end

app/controllers/superpowers_controller.rb
class SuperpowersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:root, :index, :show]

  def index
    # Superpower.reindex
    @superpowers = Superpower.all
    #@superpowers = Superpower.search_by_name_and_price(params[:query])

    @superpowers = Superpower.search_by_name_and_price(params[:query]) if params[:query].present?

      if params[:range] == "100"
        @superpowers = @superpowers.select { |superpower| superpower.price > 100 }
      elsif params[:range] == "50"
        @superpowers = @superpowers.select { |superpower| superpower.price > 50 && superpower.price < 100  }
      elsif params[:range] == "0"
        @superpowers = @superpowers.select { |superpower| superpower.price <= 50 && superpower.price > 0}
      else
        @superpowers
      end

  end


  # def filter_by_price(superpowers)
  #   if params[:price] <= 50


  # end

  def show
    @superpower = Superpower.find(params[:id])
    @bookings = Booking.where(superpower_id: params[:id])
    @booking = Booking.new
    @power = Superpower.geocoded #returns flats with coordinates

    @markers = @power.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude
      }
    end
    # @bookings = @superpower.bookings
  end

  def new
    @superpower = Superpower.new
  end

  def create
    @superpower = Superpower.new(superpower_params)
    @superpower.user = current_user
    @superpower.availability = true
    if @superpower.save
      redirect_to superpowers_path
    else
      render :new
    end
  end

  def edit
    @superpower = Superpower.find(params[:id])
  end

  def update
    @superpower = Superpower.find(params[:id])
    if @superpower.update(superpower_params)
      redirect_to dashboard_path
    else
      render :edit
    end
  end

  def destroy
    set_superpower
    @superpower.destroy
    redirect_to dashboard_path
  end


  private

  def set_superpower
    @superpower = Superpower.find(params[:id])
  end

  def superpower_params
    params.require(:superpower).permit(:name, :description, :photo, :price)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to dashboard_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :bio, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/create.html.erb
<%= render 'shared/navbar' %>
<h1>Bookings#create</h1>
<p>Find me in app/views/bookings/create.html.erb</p>

app/views/bookings/destroy.html.erb
<%= render 'shared/navbar' %>
<h1>Bookings#destroy</h1>
<p>Find me in app/views/bookings/destroy.html.erb</p>

app/views/bookings/edit.html.erb
<h2>Edit <%= @booking.user.name %></h2>
<div class=“pt-10”>
 <%= simple_form_for @booking do |f| %>
   <%= f.input :date %>
   <%= f.submit %>
 <% end %>
</div>

app/views/bookings/new.html.erb
<%= render 'shared/navbar' %>
<div class="container">
<h2 style="padding-top: 130px;">Pick your date to book "<%= @superpower.name%>"</h2>
<div class="pt-1">
  <%= simple_form_for [@superpower, @booking] do |f| %>
    <%= f.input :date %>
    <div align="center">
      <%= f.submit("Confirm Booking", class: "btn btn-secondary mt-2") %>
    </div>
  <% end %>

    <div align="center">
      <p><%= link_to "Back to SuperPowers", superpower_path(@superpower), class: 'btn btn-outline-dark mt-4' %></p>
    </div>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css?family=Mukta+Mahee:200,300,400|Abril+Fatface:400,700" rel="stylesheet">
    <title>Power Up!</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>

    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <script src='https://api.mapbox.com/mapbox-gl-js/v1.2.0/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v1.2.0/mapbox-gl.css' rel='stylesheet' />
  </head>
  <body>



    <%= yield %>


  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>


  </body>
</html>

app/views/pages/dashboard.html.erb
<%= render 'shared/navbar' %>
<div class="container" style="padding-top: 100px;">
    <h2 style ="text-align: center;"><strong>Your Dashboard</strong></h2>
  <div div class="bio-box " style="width: 900px;padding-bottom: 35px;">

    <div class="user-box text-center">
      <h4>Welcome <%= @user.name %></h4>
      <h5 class="text-center pt-5">Bio</h5>
      <p class ="text-center">Bio <%= @user.bio %></p>
    </div>

  </div>
  <div class="buttons-box">
      <p class="text-center"><%= link_to "Edit profile", edit_user_path(@user), id: "edit-button" %></p>
       <p class="text-center"><%= link_to "Back to Superpowers", superpowers_path, id: "edit-button" %></p>
  </div>

  <div class="whole-box">
    <div class="booking-box my-5 " style="width: 900px;height: 300px;">
      <div class="col-12" width="100%" >
        <% @user.superpowers.each do |superpower| %>
        <div class="row">
          <div class="col-3 my-2">
            <%= link_to superpower_path(superpower) do %>
              <img id="dash-card" src="<%=superpower.photo%>" height="50" width="50"/>
            <% end %>
          </div>
          <div class="col-4 my-2">
            <%= superpower.name%>
          </div>
          <div class="col-2 my-2">
            <% if superpower.bookings.present? %>
            <% superpower.bookings.each do |booking| %>
              <p> booked on <%= booking.date %> </p>
            <% end %>
            <% else  %>
              <p>Currently No Booking</p>
            <%end%>
          </div>
          <div class="col-1 my-2">
            <%= "€#{superpower.price}"%>
          </div>
          <div class="col-1 my-2">
            <%= link_to "Edit", edit_superpower_path(superpower)%>
          </div>
          <div class="col-1 my-2">
            <% if superpower.bookings.present? %>
              <%= link_to "Delete", superpower_path(superpower), method: :delete, data: { confirm: "This superpower was booked by someone!!! Do you REALLY want to delete?" } %>
            <% else %>
              <%= link_to "Delete", superpower_path(superpower), method: :delete, data: { confirm: "Are you sure to delete your superpower?" } %>
            <% end %>
          </div>

        </div>
          <% end %>
      </div>
    </div>

  <div class="booking-box my-5" style="width: 900px;height: 300px;">
    <div class="col-12" width="100%" >
      <div>
         <div class="row" style="text-align: center;margin: 0 auto;">
          <div class = "col-12 my-2">
            <h4>Your upcoming bookings</h4>
          </div>
          <div class="booking-view">
            <% @user.bookings.each do |booking| %>
              <div style ="padding: 10px 24px";>
              <% if booking.date > Time.now %>
              <img id="dash-card" src="<%=booking.superpower.photo%>" height="50" width="50"/>
              <div class ="detail">
                <p><%= booking.superpower.name %> </p>
                <p><%= booking.date %></p>
              </div>
              <div class ="edit-delete buttons" style="padding-top: 20px;">
                <span><%= link_to 'Edit', edit_booking_path(booking), id: "btn btn-secondary"%></span>
                <span><a data-confirm="Are you sure?" rel="nofollow" data-method="delete" href="/bookings/<%= booking.id %>">Destroy</a></span>
              </div>
              <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    </div>

  <div class="booking-box my-5" style="width: 900px;height: 300px;">
    <div class="col-12" width="100%" >
      <div>
         <div class="row" style="text-align: center;margin: 0 auto;">
          <div class = "col-12 my-2">
            <h4>Your past bookings</h4>
          </div>
          <div class="booking-view">
              <% @user.bookings.each do |booking| %>
              <div style ="padding: 10px 24px";>
               <% if booking.date < Time.now %>
                <img id="dash-card" src="<%=booking.superpower.photo%>" height="50" width="50"/>
              <div class ="detail">
                <p><%= booking.superpower.name %> </p>
                <p><%= booking.date %></p>
              </div>
              <div class ="review-button">
                <span> <%= link_to 'Leave Review', new_booking_review_path(booking), class: 'btn btn-secondary' %></span>
              </div>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
      </div>
    </div>
  </div>

app/views/pages/home.html.erb
    <header class="site-header" style="padding: 18px">
        <div class="nav-row">
          <div class="col-4 site-logo" data-aos="fade" ><%= link_to "PowerUp", root_path, class: "animsition-link"  %></div>
          <div class="col-8">
            <div class="menu">
              <ul class="navbar-menu">
                 <% if user_signed_in? %>
                <li>
                  <%= link_to "Log Out", destroy_user_session_path, class: "nav-link", method: :delete %>
                </li>
              <% else %>
                <li>
                  <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
                </li>
              <% end %>
                <% if user_signed_in? %>
                  <li class="nav-item dropdown">
                  <%= link_to dashboard_path do %>
                    <% if current_user.photo? %>
                      <%= cl_image_tag current_user.photo, height: 50, crop: :fill, class: "avatar" %>
                    <% else %>
                      <%= image_tag"http://morrisinsurancegroup.com/wp-content/uploads/2018/01/blank-avatar.png", class: 'avatar' %>
                    <% end %>
                  <% end %>
                </li>
              <% end %>

              </ul>
            </div>
          </div>
        </div>
  </header>

    <section class="site-hero overlay" style="background-image: url(https://images.unsplash.com/photo-1531907700752-62799b2a3e84?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80)">
      <div class="container">
        <div class="row site-hero-inner justify-content-center align-items-center">
          <div class="col-md-10 text-center">
            <h1 class="heading mb-4" data-aos="fade-up">Book &amp; enjoy SuperPower</h1>
            <p class="sub-heading mb-5" data-aos="fade-up" data-aos-delay="100">
            Become a SuperHero for a day
            </p>
            <p class="pt-4" data-aos="fade-up" data-aos-delay="100">
              <%= link_to 'Discover Magic Powers', superpowers_path, class: "btn uppercase btn-outline-light d-sm-inline d-block py-3" %>
            </p>
          </div>
        </div>
      </div>
    </section>

    <div class="container" style="padding-bottom: 80px;">
    <h2 class="text-center" style="padding:40px;">What our customers have to say ...</h2>
    <div class="cards">

      <div class="card">
        <img class="img-fluid" src="https://k61.kn3.net/2/B/4/D/5/2/2A9.jpg" alt="Responsive image">
        <h4 class="text-center" style="padding: 10px;">Clark Kent</h4>
        <p class= "text-center" style="color:black;">I really trust in these guys to get my superpowers and fight crime. 100% recommended!</p>
      </div>

      <div class="card">
        <img class="img-fluid" src="https://www.hindustantimes.com/rf/image_size_640x362/HT/p1/2014/07/23/Incoming/Pictures/1243711_Wallpaper2.jpg" alt="Responsive image">
        <h4 class="text-center" style="padding: 10px;">Bruce Wayne</h4>
        <p class="text-center" style="color:black;">I don't really have Superpowers, but I enjoy expending all my money on these people just to see how it feels to be a Superhero for a day</p>
      </div>

      <div class="card">
        <img class="img-fluid" src="https://i0.wp.com/www.4ye.co.uk/wp-content/uploads/2019/04/5c16a6fa01c0ea15eb58edd2-750-563.jpg?fit=750%2C563&w=640" alt="Responsive image">
        <h4 class="text-center" style="padding: 10px;">Peter Parker</h4>
        <p class="text-center" style="color:black;">With the help of PowerUp I was finally able to acquire some good superpowers and make a good impression on Mary Jane Watson.</p>
      </div>

    </div>
  </div>

  <!-- code a footer -->
  <div class="footers">
    <div class="links">
      <a href="#"><i class="fab fa-fw fa-facebook-f" style="color:white;"></i></a>
      <a href="#"><i class="fab fa-fw fa-github" style="color:white;"></i></a>
      <a href="#"><i class="fab fa-fw fa-twitter" style="color:white;"></i></a>
      <a href="#"><i class="fab fa-fw fa-instagram" style="color:white;"></i></a>
      <p style="padding: 20px;">This website was coded with <i class="fas fa-heart"></i> by "Many Hands" team at Le Wagon.</p>

    </div>
  </div>

app/views/reviews/new.html.erb
<%= render 'shared/navbar' %>
<div class="container">
<h1 class="text-center" style="padding-top: 150px;">Make a review!</h1>

<div class="pt-5">
  <%= simple_form_for [@booking, @review] do |f| %>
    <%= f.input :rating, collection: [0, 1, 2, 3, 4, 5] %>
    <%= f.input :description, class: "text-left" %>
    <div class="container text-center"><%= f.submit("Add review", class: "btn btn-secondary text-center") %></div>
  <% end %>
</div>
</div>

app/views/reviews/show.html.erb
<%= render 'shared/navbar' %>

<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/shared/_navbar.html.erb
<header class="site-header" style="padding: 18px">
        <div class="nav-row partial" style="color: black">
          <div class="col-4 site-logo" data-aos="fade" ><%= link_to "PowerUp", root_path, class: "animsition-link"  %></div>
          <div class="col-8">
            <div class="menu">
              <ul class="navbar-menu">
              <% if user_signed_in? %>
                <li>
                  <%= link_to "Log Out", destroy_user_session_path, class: "nav-link", method: :delete %>
                </li>
              <% else %>
                <li>
                  <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
                </li>

              <% end %>
              <% if user_signed_in? %>
              <li class="nav-item dropdown">
                <%= link_to dashboard_path do %>
                  <% if current_user.photo? %>
                    <%= cl_image_tag current_user.photo, height: 50, crop: :fill, class: "avatar" %>
                  <% else %>
                    <%= image_tag"http://morrisinsurancegroup.com/wp-content/uploads/2018/01/blank-avatar.png", class: 'avatar' %>
                  <% end %>
                <% end %>
              </li>
              <% end %>


              </ul>
            </div>
          </div>
        </div>
  </header>

app/views/superpowers/destroy.html.erb
<%= render 'shared/navbar' %>

<h1>Superpowers#destroy</h1>
<p>Find me in app/views/superpowers/destroy.html.erb</p>

app/views/superpowers/edit.html.erb
<%= render 'shared/navbar' %>
<div class="container">
  <h2 class="text-center" style="padding-top: 90px;">Edit your SuperPower</h2>
  <div class="pt-5">
  <%= simple_form_for @superpower do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :price, as: :numeric %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.submit "Save", class: "btn btn-secondary", style: "color: white" %>
  <% end %>
</div>
</div>

app/views/superpowers/index.html.erb
<%= render 'shared/navbar' %>

  <div class="container">
  <h1 class="text-center" style="padding-top:120px; padding-bottom: 30px;">Choose your SuperPower!</h1>

  <div class="search d-flex">

  <%= form_tag superpowers_path, method: :get, class: 'search-form text-center' do %>

  <%= text_field_tag :query,
    params[:query],
    class: "form-control",
    placeholder: "Did you have something in mind?"
  %>

  <%#= text_field_tag :price,
    params[:price],
    class: "form-control",
    placeholder: "Price?"
  %>

<%= select_tag :range, raw("<option>Price</option><option value='0'>€ (0-50)</option><option value='50'>€€ (50 -100)</option><option value='100'>€€€ (100+)</option>")%>
  <%= submit_tag "Search", class: "btn btn-primary ml-2" %>


<%# select_tag(name, option_tags = nil, options = {}) %>


  <% end %>

  </div>

  <div class="cards">
    <% @superpowers.each do |superpower| %>
      <div class="card-category" style="z-index: 100; background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path superpower.photo, crop: :fill %>'); height: 200px;">
        <%= link_to superpower.name, superpower_path(superpower) %>
        <div id="price-card">
          <% if superpower.price >= 101 %>
            <%= "€€€"%>
          <% elsif superpower.price > 51 && superpower.price < 101 %>
            <%= "€€"%>
          <% elsif superpower.price < 51 && superpower.price >= 0 %>
            <%= "€"%>
            <% end %>
        </div>
      </div>
    <% end %>
  </div>

  <br>
  <br>

  <div class="text-center"><span class="btn btn-secondary text-center" style="margin: 0 auto;"><%= link_to "Create new superpower 🚀", new_superpower_path, style: "color: white;" %></span>
  </div>
</div>

app/views/superpowers/new.html.erb
<%= render 'shared/navbar' %>
<div class="container">
  <h2 class="text-center" style="padding-top: 90px;">Create your own SuperPower!</h2>
  <div class="pt-5">
  <%= simple_form_for @superpower do |f| %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :price, as: :numeric %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
    <%= f.submit "Create SuperPower", class: "btn btn-secondary", style: "color: white" %>
  <% end %>
</div>
</div>

app/views/superpowers/show.html.erb
<%= render 'shared/navbar' %>
<div class="show-conatiner" style="text-align: center;padding-top: 95px;">
    <br>
      <h1 style="padding-bottom: 25px;">
        <strong><%= @superpower.name %></strong>
      </h1>
        <div><%= cl_image_tag @superpower.photo, height: 300, crop: :fill, class: "show-image" %>
        </div>
        <div class="font-italic pt-5" style="font-size: 25px; padding: 5px; "><%= @superpower.description %>
        </div>
        <div style="font-size: 40px; padding: 5px;"><%= "€#{@superpower.price} per day" %>
        </div>

          <!-- <div
            id="map"
            style="width: 100%;
            height: 200px;"
            data-markers="<%= @markers.to_json %>"
            data-mapbox-api-key="<%=  %>">Map here
          </div> -->

  <h3 style="padding-top: 40px;">Unavailable dates</h3>
  <ul>

<% if @superpower.bookings.present? %>
    <li class="text-center" style="list-style: none;"><% @superpower.bookings.each do |f| %>
        <div style="color: black; padding-right: 40px;">Booked on <%= f.date %></div>
        <% end %>
    </li>

  <%else%>

    <li class="text-center pt-5" style="list-style: none;">
        <div style="color: black; padding-right: 40px;">Be the first to make a booking</div>
    </li>
  <% end %>

  </ul>


  <h2 style="padding-top: 40px;">Pick your date to book "<%= @superpower.name%>"</h2>
  <div class="container pt-1" style="width: 600px">
    <%= simple_form_for [@superpower, @booking] do |f| %>
      <%= f.input :date %>
      <div align="center">
        <%= f.submit("Confirm Booking", class: "btn btn-secondary mt-2 mb-3") %>
      </div>
    <% end %>
  </div>

  <p><%= link_to "Back to All Superpowers", superpowers_path, class: 'btn btn-outline-dark' %></p>
  <div class="edit-delete">

  </div>
  <div>
    <h2 class ="pb-5">Reviews:</h2>
  <% if @superpower.reviews.present? %>
    <p>
      <% @superpower.reviews.each do |review| %>
        <% review.rating.times do  %>
          <span class="fas fa-star"></span>
        <% end %>
        <% review.blank_stars.times do  %>
          <span class="far fa-star"></span>
        <% end %>
        <br />
        <%= "\"#{review.description}\"" %>
      <br />
      <br />
      <% end%>
    </p>
  <%else%>

  <%#= link_to ‘Go to your Dashboard to make a review’, dashboard_path, class: ‘btn btn-secondary’ %>
      <p class = "pb-5">Go to your Dashboard to make a review</p>
  <% end %>

  </div>

  </div>

app/views/users/edit.html.erb
<%= render 'shared/navbar' %>

<div class="container" style="padding-top: 90px;">
  <h1>Edit your profile:</h1>
    <div class=“pt-10”>
     <%= simple_form_for @user do |f| %>
       <%= f.input :name %>
       <%= f.input :bio %>
       <%= f.input :email %>
       <%= f.input :photo %>
       <%= f.input :photo_cache, as: :hidden %>
       <%= f.submit("Save", class: "btn btn-secondary") %>
     <% end %>

     <p><%= link_to "Go back", dashboard_path, class: 'btn btn-outline-dark mt-5' %></p>
  </div>
</div>